[project]
name = "pymarkdoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown-it-py>=4.0.0",
    "pdoc>=16.0.0",
    "pytest>=9.0.2",
]

[project.scripts]
pymarkdoc-docs = "pymarkdoc._docs:main"
